{
  "build": {
    "image": "readthedocs/build:latest",
    "apt_packages": []
  },
  "conda": null,
  "mkdocs": {
    "configuration": null,
    "fail_on_warning": false
  },
  "python": {
    "install": [
      {
        "requirements": null
      }
    ],
    "version": 3,
    "use_system_site_packages": false
  },
  "search": {
    "ignore": [],
    "ranking": {}
  },
  "sphinx": {
    "builder": "sphinx",
    "configuration": "/home/docs/checkouts/readthedocs.org/user_builds/fcuff/checkouts/latest/docs/conf.py",
    "fail_on_warning": false
  },
  "doctype": "sphinx",
  "formats": [
    "htmlzip",
    "epub",
    "pdf"
  ],
  "version": "1",
  "submodules": {
    "exclude": [],
    "include": "all",
    "recursive": true
  }
}
