[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fcuff"
authors = [{name = "Thiago", email = "tabrantedaco2023@fau.edu"}]
dynamic = ["version", "description"]
