name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      run: sudo apt-get update
      run: sudo apt-get upgrade
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
      - name: Install dependencies
      run: pip install -r docs/requirements.txt
    - uses: -H actions/checkout@v4
      with:
        persist-credentials: false
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
